# Generated by Django 4.2.3 on 2023-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_file_doc_alter_file_img_alter_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
