# Generated by Django 4.2.3 on 2023-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_alter_file_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text_content',
        ),
        migrations.AddField(
            model_name='file',
            name='txt',
            field=models.FileField(blank=True, null=True, upload_to='txts/'),
        ),
    ]
