# Generated by Django 4.2.4 on 2023-08-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_file_is_shared_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_url', to='cloud.file'),
        ),
    ]
