# Generated by Django 4.2.4 on 2023-08-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_alter_shorturl_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
