# Generated by Django 4.2.4 on 2023-10-19 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0008_alter_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='viewers',
            field=models.ManyToManyField(related_name='short_urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
