# Generated by Django 4.2.4 on 2023-10-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_shorturl_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
